### ISSUE TITLE
[Question] Don't I need a "test starting token" ?

### ISSUE THREAD

**Issue by HugoFerrant** [codingbadger/instant-tokens.com#1]
Hello,
I've read on [instagram-token-agent github](https://github.com/companionstudio/instagram-token-agent) and on [instafeed github](https://github.com/stevenschobert/instafeed.js/wiki/Facebook-app-and-test-user-setup) that I should creat a facebook app in order to get something called a "test starting token". In your wiki, you also talk about the facebook app creation, but do not mention the starting token, or where do I have to supply it on instant-tokens.com
Let me know if something is unclear !
Have a good day
Hugo

**Comment by codingbadger** [comment]
Hello,

Instant-Tokens.com doesn't require you to generate any tokens.  All you need to do is authorise the Instant Tokens Instagram Application access to your account. Instant-Tokens.com will then generate and refresh your access tokens automatically.

You can then use the Instant-Tokens API endpoint to get your access token. This is the token that you would use in Instafeed.

More details on how Instant Tokens works is in the wiki https://github.com/codingbadger/instant-tokens.com/wiki/1.-Getting-Started


Hope that helps!

Thanks

Barry

**Comment by HugoFerrant** [comment]
Ok, so basically, you submitted (when first created codingbadger/instant-tokens.com) a facebook app, so that we (user of instant-tokens.com) don't have to ?

**Comment by codingbadger** [comment]
> Ok, so basically, you submitted (when first created codingbadger/instant-tokens.com) a facebook app, so that we (user of instant-tokens.com) don't have to ?

Yep pretty much, you grant access to your account to the Instant Tokens Instagram Application and it takes care of keeping your token refreshed etc.

**Comment by HugoFerrant** [comment]
Ok ! Instafeed doc/wiki was confusing because they clearly say "To authorize Instafeed.js to fetch your media you'll need to create a Facebook app, and add your Instagram user account as a test user" although it is only needed when using the instagram-token-agent and not needed with your instant-tokens.com service

**Comment by codingbadger** [comment]
Yes, that is correct. If you use InstantTokens you can use something similar to the demo here https://github.com/codingbadger/instant-tokens.com/wiki/3.-Instafeed.js-Demo

**Comment by HugoFerrant** [comment]
Thanks a lot for your quick answers and clarifications !
