### ISSUE TITLE
token expired

### ISSUE THREAD

**Issue by shamotj** [codingbadger/instant-tokens.com#11]
I red similar issue #8 and I think something is still not fixed. This is the URL which is generated from instafeed.js 

[https://graph.instagram.com/me/media?fields=caption,id,media_type,media_url,permalink,thumbnail_url,timestamp,username&access_token=IGQVJYeXY1dkoxUXNwbjhGR0lHX0dBc2QtREtyWHZAlQV9NbHZA3MThPbXg4MW5xVVgxeXJPdTY0ZAk9TSm1tNi1qWERhUHFVYjB5WFFIemtoTE1GYUcyQVBPYUJVcGhKeVBVeDVWeEdB](https://graph.instagram.com/me/media?fields=caption,id,media_type,media_url,permalink,thumbnail_url,timestamp,username&access_token=IGQVJYeXY1dkoxUXNwbjhGR0lHX0dBc2QtREtyWHZAlQV9NbHZA3MThPbXg4MW5xVVgxeXJPdTY0ZAk9TSm1tNi1qWERhUHFVYjB5WFFIemtoTE1GYUcyQVBPYUJVcGhKeVBVeDVWeEdB)

And you can see it returns message "Error validating access token: Session has expired on Friday, 11-Sep-20 06:41:31 PDT. The current time is Wednesday, 18-Nov-20 06:50:07 PST.". So I believe that some tokens are still not refreshed.

**Comment by codingbadger** [comment]
Hello,

The original bug you mentioned would have caused the initial expiry. You will have to re-authorise the Instagram application in order to re-generate a valid token.

Thanks
