### ISSUE TITLE
Unable To Authorise

### ISSUE THREAD

**Issue by tobyjug** [codingbadger/instant-tokens.com#13]
After authorising an Instagram account, I'm returned to instant-tokens.com but greeted with the following:

```
Something has gone wrong, check out the error message below. If you need help head over to our GitHub to raise an issue.

{
  "error": "No Auth Code found in querystring parameters."
}

```
Within the Instagram account, Instant-Tokens.com is shown as authorised but there are no authorisations in the Instant-Tokens Dash.

**Comment by codingbadger** [comment]
Hi @tobyjug 

Apologies, this should be fixed now. Let me know if you have any further problems.

Thanks

**Comment by tobyjug** [comment]
Amazing, thanks!
