### ISSUE TITLE
*** ATTENTION : Facebook has disabled the Instant Tokens Application ***

### ISSUE THREAD

**Issue by codingbadger** [codingbadger/instant-tokens.com#14]
For reasons I am not clear on, Facebook has disabled the Instant Tokens Application with immediate effect.

I have reached out to them to find out the reasons why.  I will update this issue with information as and when I have it. 

Please do not email support

UPDATE: 14th March 2021 

The Instant Tokens Application has been reinstated by Facebook after appeal.

**Comment by kaleidografik** [comment]
Thanks for updating us on this @codingbadger - please keep us updated on any progress. This has taken down a few client sites for us and not really any alternatives out there at present, unless anyone can suggest similar?

**Comment by studiohic** [comment]
@kaleidografik - same with us and haven't found a suitable alternative - very frustrating of Facebook. @codingbadger - thanks for looking into the issue and look forward to hearing some positive news from your findings...

**Comment by codingbadger** [comment]
Hi all,

I appealed the ban with Facebook and I have just received notification that the Instant Tokens Application has been reinstated.

They haven't explained why it was disabled in the first instance.

If any tokens have expired then you will need to re-authorise the Instagram Application in order to get a new long lived token.

Thanks

**Comment by FreMun** [comment]
@codingbadger Thank you for this quick fix!!

**Comment by studiohic** [comment]
@codingbadger - Thank you for the quick fix...all the best

**Comment by codingbadger** [comment]
I have removed the FB warning from the site and re-enabled the link to `Authorise An Instagram Application`

**Comment by kaleidografik** [comment]
Thanks so much for resolving this so quickly, fingers crossed Facebook don’t do anything like this again.
