### ISSUE TITLE
Unable to authorize

### ISSUE THREAD

**Issue by manolis1g** [codingbadger/instant-tokens.com#17]
Hello 

I can't authorize an application. I'm getting this: 
Something has gone wrong, check out the error message below. If you need help head over to our GitHub to raise an issue.

                
`{
  "headers": {
    "normalizedNames": {},
    "lazyUpdate": null
  },
  "status": 500,
  "statusText": "OK",
  "url": "https://ig.instant-tokens.com/tokens/authorise?code=AQDHb0HHZjaHO42w1-0qmpwjr8SYTn4I06CeZlGcx8GAmBgnPQFOdWzIWdieiovcW38BVTVlaU5bUVlwXaCYQ4SD6eBmTpkPB8btmxDgmlTzzz27xfJDAaIn5UK8L__u5rzlaKJaPk1U1vYf21zuUzI9HKtT2QVp4oBjiTvkx_KGh-ikV6A7WtUJ4fj3W6aOUnOS5ucvUb78FO78DsPidafBjI47cQPUTk6pXff3Y68E5A",
  "ok": false,
  "name": "HttpErrorResponse",
  "message": "Http failure response for https://ig.instant-tokens.com/tokens/authorise?code=AQDHb0HHZjaHO42w1-0qmpwjr8SYTn4I06CeZlGcx8GAmBgnPQFOdWzIWdieiovcW38BVTVlaU5bUVlwXaCYQ4SD6eBmTpkPB8btmxDgmlTzzz27xfJDAaIn5UK8L__u5rzlaKJaPk1U1vYf21zuUzI9HKtT2QVp4oBjiTvkx_KGh-ikV6A7WtUJ4fj3W6aOUnOS5ucvUb78FO78DsPidafBjI47cQPUTk6pXff3Y68E5A: 500 OK",
  "error": {
    "message": "Internal Server Error"
  }
}`

Any ideas? 

Thanks
Manolis

**Comment by codingbadger** [comment]
Hi Manolis,

I have checked the logs and there were a few errors but they are from the Instagram API. I have just tried an authorisation and it worked fine. I can only assume it was something at their end.

Thanks
