### ISSUE TITLE
Is there a limit in the amount of hits to the API Endpoint?

### ISSUE THREAD

**Issue by Eddie-Silva** [codingbadger/instant-tokens.com#21]
Hi. I am having issues with Instant-tokens. A week ago instant-tokens was working fine on my website, but now it wont display my instagram feed. is there a limit to the amount of hits to the Endpoint?
I tried testing with other instagram accounts and they work fine - I see those post on the website. 

I checked the on instagram and Instant-tokens is active on the apps and websites section. I also created a new user secrete for the account but it still wont show my posts on my websites. (I've tried two other accounts and they work fine, it's just that one account that is not working.

Do you have an idea what could be the issue? 
Thanks for replying!

**Comment by codingbadger** [comment]
There is no limit in place on Instant-Tokens.com. Have you tried logging in to Instagram and deauthorising the Instant-Tokens application, then re-authorising it from your Instant tokens account. That usually solves any issues.

Let me know how you get on.

**Comment by Eddie-Silva** [comment]
Hi Barry,

I have tried that and it has solved the problem. Thank you.
