### ISSUE TITLE
Email field is not clickable on webpage because menu is above it 

### ISSUE THREAD

**Issue by kr1stjans** [codingbadger/instant-tokens.com#29]
Email field is not clickable on webpage, because menu is above it on my screen resolution. 

![image](https://user-images.githubusercontent.com/6900225/150764454-a41747d3-14ae-4fd6-b1e1-04d1d8f99d6f.png)

**Comment by codingbadger** [comment]
I have pushed out a fix for this.

Thanks for raising an issue! 👍
