### ISSUE TITLE
no link to generate token any more?

### ISSUE THREAD

**Issue by LibbyJane** [codingbadger/instant-tokens.com#31]
I'm seeing an id and secret, but nothing to actually generate the token any more?

Barry! Hi!

**Comment by codingbadger** [comment]
Hey Libby!

Small world huh? 😄 How are things?

Sorry about this, I missed the v6 update to Font Awesome. Should be there now

Thanks

Barry

**Comment by LibbyJane** [comment]
woop, perfect, thanks :)

Happy birthday for the other day!
