### ISSUE TITLE
Token works within Codepen but not in website

### ISSUE THREAD

**Issue by mikelivingston04** [codingbadger/instant-tokens.com#6]
Here is my HTML file:

`
<script src="https://ig.instant-tokens.com/users/ad0c3b27-7113-4245-b4ea-92700898dbbb/instagram/17841414290785692/token.js?userSecret=gpqqbdi5ga8z0hmein70f"></script>
<script>
    $(function(){
        console.log("insta token: " + InstagramToken);
        var feed = new Instafeed ({
            accessToken: InstagramToken
        });
        feed.run();

});
</script>
`

The console within my browser prints out:
`Uncaught Error: Error from Instagram: The access_token provided is invalid.
    at Instafeed.parse (main.ec9ab4606cecc5cd0626720852f7df80.js:3422)
    at popular?access_token=IGQVJXd09hNHpkc2tsazhwb3ZAkeWU1QWx2UktfdDdKN3VMT2lOSlpUVGxPRU1PSVBuZATVTODBWMWJJeVVnYmtVclVMVkU2OXlCOHNsWGtDNHhUYS1wQk1FSHVfeDdmU1oyUXhtZAktn&callback=instafeedCache69931a98e1554ff3.parse:1`

Both the JS file and the JSON response work fine within code pen from the examples. The token just doesn't seem to work within my HTML file. I must be missing something

**Comment by codingbadger** [comment]
I think you are using instafeed.js v1.4.1 - you need to use v2.0.0-rc2 

See the releases here https://www.npmjs.com/package/instafeed.js  the v1 release is marked as latest as v2 is not officially released.

**Comment by stevenschobert** [comment]
@codingbadger sorry, I plan on making the v2 release official — just have been busy!
