### ISSUE TITLE
Token expired (Sunday, 09-Aug-20 in my case)

### ISSUE THREAD

**Issue by hferrant** [codingbadger/instant-tokens.com#7]
I'm getting the following error in my console :

`Error : "api request error: 190 Error validating access token: Session has expired on Sunday, 09-Aug-20 01:30:58 PDT. The current time is Monday, 17-Aug-20 08:14:58 PDT."`

Is there anything I can do, or is it an issue on your side ?

Thanks,
Hugo

**Comment by codingbadger** [comment]
Hello,

Sorry for the delay, I was away on holiday.

You could always try de-authorising the instant-tokens.com application from your instagram account and re-authorising it.

If you email me your email address used to register I can have a look in the logs and see if I can find anything. My email is barry AT codingbadger DOT com

Cheers

Barry

**Comment by hferrant** [comment]
As I said before, the token is said to be expired since the 9th of August.
Seems like instant-tokens.com didn't convert it a Long Lived Access token and/or didn't keep it refreshed :stuck_out_tongue: 
I'm searching the email adress used, I'll edit this comment when I found it

**Comment by codingbadger** [comment]
This should not happen going forward. related #8
