### ISSUE TITLE
Tokens not refreshing

### ISSUE THREAD

**Issue by kaleidografik** [codingbadger/instant-tokens.com#8]
Hey @codingbadger - we've been using instant-tokens.com for a few months to power instafeed.js plugin. All has been working great but 2 sites recently expired their access tokens, and stopped working. I was under the impression that the service automatically renewed and kept on top of these tokens?

I have fixed now, but it required de-authorising and re-authoring the app, which is obviously not ideal every 60 days. Is this a bug or an expected behaviour? Anything we can do?

Thanks

**Comment by codingbadger** [comment]
Hello,

Thanks for getting in touch.

Yes, this was a bug in the refresh processing. Unfortunately, not all exceptions were being caught correctly which resulted in the entire batch being failed.

I pushed out a fix this morning so hopefully it shouldn't happen again.

Apologies for any inconvenience caused.

Thanks

Barry

**Comment by kaleidografik** [comment]
Thanks for the prompt response Barry, that’s great that a fixed has been pushed, will keep an eye on things
